app:
  name: CurrencyExchangeApp
  port: :3000

database:
  # host: localhost
  # port: :3306
  # user: root
  # password: Mysql112223
  # name: test
  dsn: root:Mysql112223@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenCons: 114